# Generated by Django 4.1.2 on 2022-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='stroe_custo_last_na_de00ff_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='stroe_customers',
        ),
    ]
